# Generated by Django 5.0.4 on 2024-05-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicarform',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='publicarform',
            name='video',
        ),
    ]
