# Generated by Django 5.0.4 on 2024-05-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar', '0002_alter_post_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='null', upload_to='posts'),
        ),
    ]
