# Generated by Django 5.0.4 on 2024-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar', '0002_remove_publicarform_foto_remove_publicarform_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicarform',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotosPost/'),
        ),
        migrations.AddField(
            model_name='publicarform',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
