# Generated by Django 4.2.10 on 2024-05-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ActualizarCuenta", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
